spring.application.name=spoticlone-backend
server.port=8080

# ─── PostgreSQL ────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://192.168.1.75:5432/spotyclone
spring.datasource.username=doof
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# Deshabilitar auto-configuracion JPA / Hibernate explicitamente
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# ─── Flyway ────────────────────────────────────────────────────────────────────
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true

# ─── MongoDB ───────────────────────────────────────────────────────────────────
spoticlone.mongodb.uri=mongodb://localhost:27017
spoticlone.mongodb.database=spoticlone_nosql

# ─── Logging ───────────────────────────────────────────────────────────────────
logging.level.unbosque.edu.co.Spoticlone=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.flywaydb=DEBUG

# ─── JWT ───────────────────────────────────────────────────────────────────────
jwt.secret=Spoticlone2026CambiarEnProduccionConClaveDeAlMenos256BitsSeguro
jwt.expiration-ms=86400000
